<template>
    <el-row>
    <el-col
    class='el-menu-vertical-demo'
    >
    <el-menu>
        <el-submenu>
            <template>
                <span>
                    哈哈哈哈哈哈12
                </span>
            </template>
        </el-submenu>
        <el-submenu>
            <template>
                <span>
                    哈哈哈哈哈哈23
                </span>
            </template>
        </el-submenu>
    </el-menu>
    </el-col>
    </el-row>
</template>
